update

diff --git a/rundocker b/rundocker
--- a/rundocker
+++ b/rundocker
@@ -1,19 +1,35 @@
 . ~/.rc
-myapp=nginx-openshift
-myorg=wavecloud
-myimage=$myorg/$myapp
-myport=8081
+image=wavecloud/nginx-std
+ port=8081
+ app=nginx
+ docker build -f Dockerfile -t $image  .
 
-echo "build and push docker images"
-docker login -uzhanghongqi -p${dockerps}
-set -x
+echo "login docker"
+docker login -u$USERNAME -p$PASSWORD
 
-docker build -f Dockerfile -t wavecloud/nginx-openshift  . 
+echo "build docker"
+docker rm -f $app
+ls -al
+docker build -f Dockerfile -t $image . 
 
-# docker push $myimage
-# docker rmi $myimage
+echo "push docker"
+docker push $image
+docker rmi $image
 
-echo "stop and start docker"
-docker rm -f mynginx
-docker run --name mynginx -p 8081:8081 -d wavecloud/nginx-openshift
+echo "deploy docker "
+docker run --name $app -d -p $port:$port $image
+
+echo "wait a whole"
+sleep 10
+
+echo "verify docker"
+if curl localhost:$port | grep 'Welcome HONGQI' ; then
+    echo "verify successfully"
+else
+    echo "ERROR: verify failure"
+    exit 1;
+fi
+
+echo "clean docker "
+docker rm -f $app
 
diff --git a/runkube b/runkube
--- a/runkube
+++ b/runkube
@@ -1,16 +1,35 @@
-. ~/.rc
-docker login -uzhanghongqi -p${dockerps}
+#!/bin/bash
+ set -x
+# MASTER=hongqi@192.168.99.110
+# scp ${MASTER}:~/.kube/config .
+# export KUBECONFIG=$(pwd)/config
 
-#docker run --name mynginx -p 8081:8081 -d wavecloud/nginx-openshift
-kubectl create deployment nginx --image=wavecloud/nginx-openshift
+ image=wavecloud/nginx-std
+ port=8081
+ app=nginx
+ docker build -f Dockerfile -t $image  .
 
+ echo "push and remove docker images"
+ docker login -uzhanghongqi -ppass
+ docker push $image
 
-#kubectl create service nodeport nginx --tcp=80:80
-kubectl expose deployment nginx --target-port=8081 --type=NodePort
-kubectl get svc
-#nginx          NodePort    10.110.83.26     <none>        80:30938/TCP   5m
- 
-#curl podNodeIP:30938
+ kubectl get pods
 
+ kubectl delete deploy $app
+ kubectl delete svc $app
 
+ kubectl create deployment $app --image=$image --port=$port
+ sleep 10
+ kubectl expose deployment $app --target-port=$port --type=NodePort
+ sleep 5
+ kubectl port-forward svc/nginx  $port:$port &
+ sleep 5
 
+ if curl localhost:$port | grep 'Welcome HONGQI' ; then
+    echo "verify successfully"
+ else
+    echo "ERROR: verify failure"
+    exit 1;
+ fi
+ pid=`ps -ax|grep port-forward | awk 'NR==1{print $1}'`
+ kill -9 $pid
